return {
	US = { emoji = "🇺🇸", name = "Estados Unidos" },
	CA = { emoji = "🇨🇦", name = "Canada" },
	MX = { emoji = "🇲🇽", name = "Mexico" },
	GU = { emoji = "🇬🇹 ", name = "Guatemala" },
	PE = { emoji = "🇵🇪", name = "Peru" },
	AR = { emoji = "🇦🇷", name = "Argentina" },
	CL = { emoji = "🇨🇱", name = "Chile" },
	CO = { emoji = "🇨🇴", name = "Colombia" },
	BR = { emoji = "🇧🇷", name = "Brazil" },
	VE = { emoji = "🇻🇪", name = "Venezuela" },
	EC = { emoji = "🇪🇨", name = "Ecuador" },
	BO = { emoji = "🇧🇴", name = "Bolivia" },
	RD = { emoji = "🇩🇴 ", name = "Republica Dominicana" },
	CU = { emoji = "🇨🇺", name = "Cuba" },
	PA = { emoji = "🇵🇦", name = "Panama" },
	NI = { emoji = "🇳🇮", name = "Nicaragua" },
	HN = { emoji = "🇭🇳", name = "Honduras" },
	SV = { emoji = "🇸🇻", name = "El Salvador" },
	CR = { emoji = "🇨🇷", name = "Costa Rica" },
	BZ = { emoji = "🇧🇿", name = "Belice" },
	PY = { emoji = "🇵🇾", name = "Paraguay" },
	TT = { emoji = "🇹🇹", name = "Trinidad y Tobago" },
	JM = { emoji = "🇯🇲", name = "Jamaica" },
	ES = { emoji = "🇪🇸", name = "España" },
	FR = { emoji = "🇫🇷", name = "Francia" },
	DE = { emoji = "🇩🇪", name = "Alemania" },
	IT = { emoji = "🇮🇹", name = "Italia" },
	GB = { emoji = "🇬🇧", name = "Reino Unido" },
	PT = { emoji = "🇵🇹", name = "Portugal" },
	PR = { emoji = "🇵🇷 ", name = "Puerto Rico" },
	GR = { emoji = "🇬🇷", name = "Grecia" },
	SE = { emoji = "🇸🇪", name = "Suecia" },
	NO = { emoji = "🇳🇴", name = "Noruega" },
	FI = { emoji = "🇫🇮", name = "Finlandia" },
	DK = { emoji = "🇩🇰", name = "Dinamarca" },
	NL = { emoji = "🇳🇱", name = "Países Bajos" },
	BE = { emoji = "🇧🇪", name = "Bélgica" },
	CH = { emoji = "🇨🇭", name = "Suiza" },
	AT = { emoji = "🇦🇹", name = "Austria" },
	PL = { emoji = "🇵🇱", name = "Polonia" },
	CZ = { emoji = "🇨🇿", name = "República Checa" },
	HU = { emoji = "🇭🇺", name = "Hungría" },
	RO = { emoji = "🇷🇴", name = "Rumania" },
	RU = { emoji = "🇷🇺", name = "Rusia" },
	TR = { emoji = "🇹🇷", name = "Turquía" },
	JP = { emoji = "🇯🇵", name = "Japon" },
	CN = { emoji = "🇨🇳", name = "China" },
	KR = { emoji = "🇰🇷", name = "Corea del sur" },
	IN = { emoji = "🇮🇳", name = "India" },
	TH = { emoji = "🇹🇭", name = "Tailandia" },
	MY = { emoji = "🇲🇾", name = "Malasia" },
	SG = { emoji = "🇸🇬", name = "Singapur" },
	ID = { emoji = "🇮🇩", name = "Indonesia" },
	PH = { emoji = "🇵🇭", name = "Filipinas" },
	VN = { emoji = "🇻🇳", name = "Vietnam" },
	TW = { emoji = "🇹🇼", name = "Taiwan" },
	HK = { emoji = "🇭🇰", name = "Hong Kong" },
	LK = { emoji = "🇱🇰", name = "Sri Lanka" },
	PK = { emoji = "🇵🇰", name = "Paquistan" },
	BD = { emoji = "🇧🇩", name = "Bangladesh" },
	NP = { emoji = "🇳🇵", name = "Nepal" },
	AF = { emoji = "🇦🇫", name = "Afganistan" },
	ZA = { emoji = "🇿🇦", name = "Sudafrica" },
	NG = { emoji = "🇳🇬", name = "Nigeria" },
	EG = { emoji = "🇪🇬", name = "Egipto" },
	MA = { emoji = "🇲🇦", name = "Marruecos" },
	DZ = { emoji = "🇩🇿", name = "Argelia" },
	TN = { emoji = "🇹🇳", name = "Tunez" },
	KE = { emoji = "🇰🇪", name = "Kenia" },
	ET = { emoji = "🇪🇹", name = "Etiopia" },
	GH = { emoji = "🇬🇭", name = "Ghana" },
	ZW = { emoji = "🇿🇼", name = "Zimbabwe" },
	BW = { emoji = "🇧🇼", name = "Botswana" },
	AO = { emoji = "🇦🇴", name = "Angola" },
	MZ = { emoji = "🇲🇿", name = "Mozambique" },
	TZ = { emoji = "🇹🇿", name = "Tanzania" },
	IL = { emoji = "🇮🇱", name = "Israel" },
	SA = { emoji = "🇸🇦", name = "Arabia Saudita" },
	AE = { emoji = "🇦🇪", name = "Emiratos Arabes Unidos" },
	LB = { emoji = "🇱🇧", name = "Libano" },
	JO = { emoji = "🇯🇴", name = "Jordania" },
	IQ = { emoji = "🇮🇶", name = "Irak" },
	IR = { emoji = "🇮🇷", name = "Iran" },
	SY = { emoji = "🇸🇾", name = "Siria" },
	YE = { emoji = "🇾🇪", name = "Yemen" },
	UR = { emoji = "🇺🇾 ", name = "Uruguay" },
	AU = { emoji = "🇦🇺", name = "Australia" },
	NZ = { emoji = "🇳🇿", name = "Nueva Zelanda" },
	IE = { emoji = "🇮🇪", name = "Irlanda" },
	IS = { emoji = "🇮🇸", name = "Islandia" },
	HR = { emoji = "🇭🇷", name = "Croacia" },
	RS = { emoji = "🇷🇸", name = "Serbia" },
	BG = { emoji = "🇧🇬", name = "Bulgaria" },
	SK = { emoji = "🇸🇰", name = "Eslovaquia" },
	SI = { emoji = "🇸🇮", name = "Eslovenia" },
	LT = { emoji = "🇱🇹", name = "Lituania" },
	LV = { emoji = "🇱🇻", name = "Letonia" },
	EE = { emoji = "🇪🇪", name = "Estonia" },
	KH = { emoji = "🇰🇭", name = "Camboya" },
	FJ = { emoji = "🇫🇯", name = "Fiji" },
	MU = { emoji = "🇲🇺", name = "Mauricio" },
	MV = { emoji = "🇲🇻", name = "Maldivas" },
}
